bind: 
  # [必填]监听地址，设为`0.0.0.0`可监听包括IPv6的所有地址
  addr: "127.0.0.1:53" 

  protocol: "all" # 监听协议，`tcp`, `udp`或`all`。留空默认`all`

# 服务器
server:
  # 用于解析大陆域名的本地服务器
  local: 
    addr: "223.5.5.5:53" # 地址，留空将禁用本地服务器
    protocol: "udp" # 协议。`tcp`, `udp`或`doh`。留空默认`udp`
    url: "https://223.5.5.5/dns-query" # DoH的url，仅`protocol`为`doh`有用且必需

    # 是否屏蔽不常见请求的类型
    # 不常见类型：包含多个Question|非A或AAAA请求
    deny_unusual_types: false

    deny_results_without_ip: false  # 是否屏蔽没有IP的A和AAAA应答

    # IP策略
    # 格式: "action:file|action:file|..."
    # 返回的应答IP将根据此策略判断是接受还是丢弃，可由多个策略构成，用`|`分割，
    # 处理流程从左至右，如果上一条策略没有命中，将匹配下一条
    # 如果直到最后都没有命中任何策略，默认处理方式为`accept`
    #
    # `file`为IP表的路径，IP表格式参见[这里](#ip表格式)
    # `action`可以是：
    #   `accept`: 如果IP在`file`中，接受返回的应答
    #   `deny`: 如果IP在`file`中，拒绝返回的应答
    #   `deny_all`: 无条件拒绝，用在最后，拒绝所有之前没有命中的应答
    #     相当于把默认处理方式改为`deny`，后不需要跟`file`
    #  
    # e.g. "deny:./blacklist.txt" 屏蔽`blacklist.txt`里的IP
    # e.g. "accept:./whitelist.txt|deny_all" 仅允许`whitelist.txt`里的IP
    # e.g. "deny:./blacklist.txt|accept:./whitelist.txt|deny_all"
    ip_policies: "accept:./chn.list|deny_all"

    # 域名策略
    # 格式: "action:file|action:file|..."
    #
    # 域名分流策略决定请求的域名被谁解析，可由多个策略构成，用`|`分割
    # 处理流程从左至右，如果上一条策略没有命中，将匹配下一条
    # 如果直到最后都没有命中任何策略，默认处理方式为`accept`
    #
    # `file`为域名表的路径，域名表格式参见[这里](#域名表格式)
    #
    # `action`可以是
    #   `force`: 如果域名在`file`中，强制该请求只送至本地服务器
    #     并且最终应答会无视其他所有匹配条件，强制被接受
    #   `accept`: 如果域名在`file`中，请求会送至本地服务器
    #   `deny`: 如果域名在`file`中，请求不会送至本地服务器
    #   `deny_all`: 无条件拒绝，用在最后，拒绝所有之前没有命中的应答
    #      相当于把默认处理方式改为`deny`，后不需要跟`file`
    # 
    # e.g. "deny:./blacklist.txt" 屏蔽`blacklist.txt`里的域名
    # e.g. "force:./whitelist.txt" 强制本地服务器解析`whitelist.txt`里的域名
    # e.g. "force:./whitelist.txt|deny_all" 不在其中的域名会一定由远程服务器解析
    # e.g. "force:./chn_domain.list|accept:./whitelist.txt|deny_all"
    domain_policies: "force:./chn_domain.list"

    # 域名策略是否也检查返回应答中的CNAME记录(CNAME深度检查)
    # 可能会使域名分流更准确，特别是一些使用了CDN的域名
    check_cname: false

  # 用于解析国际域名的远程服务器
  remote:
    addr: "1.0.0.1:443" # 地址，留空将禁用远程服务器
    protocol: "doh" # 协议。`tcp`, `udp`或`doh`。留空默认`udp`
    url: "https://cloudflare-dns.com/dns-query" # DoH的url，仅`protocol`为`doh`有用且必需

    # 延时启动时间 单位: 毫秒 
    # 如果在设定时间后本地服务器无应答，则开始请求远程服务器
    # 在等待中，如果本地服务器失败或应答被丢弃，会中止等待立即开始请求远程服务器
    # 将该值设定为约120%的本地服务器的延时可显著降低请求远程服务器的次数
    # 该选项能牺牲一点延时来降低设备最多一半的负载
    # `0`表示禁用延时，请求将同步发送
    delay_start: 50
    
  
# EDNS Client Subnet
# 格式: `CIDR` 支持IPv6
# 如果填入，发出至`local/remote`的请求将插入ECS信息
# 如果来自下游的请求已包含ECS，则不会插入或复写
# e.g. "1.2.3.0/24"
# e.g. "2001:dd8:1a::/48"
ecs:
  local: ""
  remote: ""

# CA证书
# 如果系统自带证书不可用。只有导入证书后TLS才能实现服务器身份验证，DoH才能工作
# 出于安全考虑mos-chinadns不提供能绕过身份验证的选项
# 证书需为PEM格式，支持ca-bundle
# 默认留空，自带使用系统证书
ca:
  path: "" # CA证书路径
